version: '3'
services:
  dappstore:
    image: dappstore_server
    environment:
      - PORT=3002
      - NODE_ENV=production
    ports:
      - 3002:3002
    build:
      context: .
      dockerfile: Dockerfile
