version: '3'
services:
  dappstore:
    image: dappstore_front
    environment:
      - PORT=3003
      - NODE_ENV=production
    ports:
      - 3003:3003
    build:
      context: .
      dockerfile: Dockerfile
