version: '3'
services:
  dappstore:
    image: dappstore_front
    environment:
      - PORT=3030
      - NODE_ENV=production
    ports:
      - 3030:3030
    build:
      context: .
      dockerfile: Dockerfile
